# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: /
#url: http://mazhuang.org#
date_format: "ordinal"
title: 国风
subtitle: "RTFSC万丈高楼平地起，勿在浮沙筑高台"
label: "插件化、Hybrid H5混合开发、组件化路由、热修复"
description: "国风的个人博客"
keywords: Guo feng, 天风静静
resume: https://guofeng007.github.io/anires/public/
resume_name: 简历
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Guo Feng
organization: baidu.com
organization_url: http://www.baidu.com
github_username: guofeng007
location: Beijing, China
email: tianfengjingjing@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: guofeng007/guofeng007.github.io

